require('lazy').setup({
  { import = 'plugins.lsp' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.ui' },
  { import = 'plugins.debug' },
  { import = 'plugins.misc' },
  { import = 'plugins.autopairs' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.lint' },
  { import = 'plugins.flash' },
  { import = 'plugins.fidget' },
  { import = 'plugins.vim-tpipeline' },
  { import = 'plugins.vim-tmux-navigator' },
  { import = 'plugins.move' },
  { import = 'plugins.neogit' },
  { import = 'plugins.snacks' },
  { import = 'plugins.navigation' },
  { import = 'plugins.tasks' },
  { import = 'plugins.quickfix' },
  { import = 'plugins.render-markdown' },
  { import = 'plugins.noice' },
  { import = 'plugins.obsidian' },
  { import = 'plugins.pomo' },
}, {
  checker = { enabled = true },
  change_detection = { notify = false },
})
